// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../bad/constants/cssclassmap.js', ['bad.CssClassMap'], ['bad.CssPrefix'], {});
goog.addDependency('../../../../bad/constants/cssprefix.js', ['bad.CssPrefix'], [], {});
goog.addDependency('../../../../bad/math/bit.js', ['bad.math.bit'], [], {'module': 'goog'});
goog.addDependency('../../../../bad/math/buff.js', ['bad.math.buff'], [], {'module': 'goog'});
goog.addDependency('../../../../bad/ui/button.js', ['bad.ui.button'], ['bad.utils', 'goog.array', 'goog.dom', 'goog.ui.Component', 'goog.ui.ContainerRenderer', 'goog.ui.ControlRenderer', 'goog.ui.Css3ButtonRenderer', 'goog.ui.Css3MenuButtonRenderer', 'goog.ui.CustomButton', 'goog.ui.Menu', 'goog.ui.MenuButton', 'goog.ui.MenuItem', 'goog.ui.MenuItemRenderer', 'goog.ui.MenuRenderer', 'goog.ui.MenuSeparator', 'goog.ui.ToggleButton'], {});
goog.addDependency('../../../../bad/ui/component.js', ['bad.ui.Component'], ['bad.CompEvent', 'bad.EventType', 'goog.style', 'goog.ui.Component'], {});
goog.addDependency('../../../../bad/ui/events/compevent.js', ['bad.CompEvent'], ['goog.events.Event'], {});
goog.addDependency('../../../../bad/ui/events/uieventtype.js', ['bad.EventType', 'bad.ui.Resizable.EventType'], ['bad.utils'], {});
goog.addDependency('../../../../bad/ui/events/viewevent.js', ['bad.ViewEvent'], ['goog.events.Event'], {});
goog.addDependency('../../../../bad/ui/exclusivebuttongroup.js', ['bad.ui.ExButtonGroup'], ['goog.events.EventHandler', 'goog.ui.Component'], {});
goog.addDependency('../../../../bad/ui/form.js', ['bad.ui.FieldErrs', 'bad.ui.Form'], ['bad.ui.Panel', 'bad.utils', 'goog.dom', 'goog.dom.TagName', 'goog.dom.classlist', 'goog.dom.forms', 'goog.events.EventType', 'goog.uri.utils'], {});
goog.addDependency('../../../../bad/ui/layout/layout.js', ['bad.ui.Layout', 'bad.ui.Layout.CssClassMap', 'bad.ui.Layout.IdFragment'], ['bad.CssPrefix', 'bad.EventType', 'bad.ui.Component', 'goog.dom', 'goog.dom.TagName', 'goog.dom.ViewportSizeMonitor', 'goog.dom.classlist', 'goog.events.Event', 'goog.events.EventType', 'goog.fx.Animation', 'goog.fx.Dragger', 'goog.fx.Transition', 'goog.math.Box', 'goog.math.Rect', 'goog.math.Size', 'goog.object', 'goog.style', 'goog.ui.Component'], {});
goog.addDependency('../../../../bad/ui/layout/shape_to_layout.js', ['bad.layout.parseShape'], ['bad.layout.shapesNames'], {'module': 'goog'});
goog.addDependency('../../../../bad/ui/layout/shapes.js', ['bad.layout.shapesNames'], [], {'module': 'goog'});
goog.addDependency('../../../../bad/ui/panel.js', ['bad.ui.Panel'], ['bad.CssClassMap', 'bad.ui.Component', 'bad.utils', 'goog.Uri', 'goog.dom', 'goog.dom.TagName', 'goog.format.JsonPrettyPrinter'], {});
goog.addDependency('../../../../bad/ui/view.js', ['bad.ui.View'], ['bad.EventType', 'bad.ViewEvent', 'goog.events.EventHandler', 'goog.events.EventTarget'], {});
goog.addDependency('../../../../bad/user/usermanager.js', ['bad.UserManager'], ['goog.net.cookies', 'goog.uri.utils'], {});
goog.addDependency('../../../../bad/util/func.js', ['bad.func'], [], {'module': 'goog'});
goog.addDependency('../../../../bad/util/utils.js', ['bad.utils'], ['goog.array', 'goog.dom', 'goog.object', 'goog.string'], {});
